module.exports = {
  name: "Micro Office",
  baseUrl: "https://www.microofficeml.com",
  tagline: "Imaginons. Visualisons. Réalisons.",
  since: 2014,
  email: "infos@microofficeml.com",
  // TODO (Micro Office) : confirmer/compléter le numéro de téléphone fixe si différent du WhatsApp.
  phoneDisplay: "+223 89 46 00 00",
  phoneHref: "tel:+22389460000",
  whatsappNumber: "22389460000",
  addressLine: "Bamako, Mali",
  trustedClients: [
    { name: "NBB", file: "nbb.png" },
    { name: "BAH Automobile", file: "bah-automobile.png" },
    { name: "COOFIX & EMS", file: "ems.png" },
    { name: "SSE — Sonikara Solar Electro", file: "sse.png" },
    { name: "AMADER", file: "amader.png" },
    { name: "BK Gaz", file: "bk-gaz.png" },
    { name: "Balim", file: "balim.png" },
    { name: "FEBAK — Thé Andalousi", file: "the-andalousi-febak.png" },
    { name: "Gandhi Malien TV", file: "gandhi-malien-tv.png" },
    { name: "Thé Barika", file: "the-barika.png" },
    { name: "Oryx Energies", file: "oryx-energies.png" },
    { name: "IRA", file: "ira.png" },
    { name: "GB Carrières & BTP", file: "gb-carrieres-btp.png", dark: true },
    { name: "Hollantex", file: "hollantex.png" },
    { name: "Partenaire Micro Office", file: "partenaire.png" }
  ],
  socials: {
    instagram: "",
    facebook: "",
    linkedin: "",
  },
  legal: {
    formeJuridique: "[À COMPLÉTER — forme juridique]",
    rccm: "[À COMPLÉTER — n° RCCM]",
    nif: "[À COMPLÉTER — NIF]",
    siege: "[À COMPLÉTER — adresse du siège]",
  },
  nav: [
    { label: "Accueil", url: "/" },
    { label: "Solutions", url: "/solutions/" },
    { label: "Réalisations", url: "/realisations/" },
    { label: "Boutique", url: "/boutique/" },
    { label: "À propos", url: "/a-propos/" },
    { label: "Contact", url: "/contact/" },
  ],
  formspreeEndpoint: "https://formspree.io/f/VOTRE_ID_FORMSPREE",
};
